export const ADD_RESTO_DATA = "ADD_RESTO_DATA";
export const PENDING_RESTO_DATA = "PENDING_RESTO_DATA";
export const REMOVE_RESTO_DATA = "REMOVE_RESTO_DATA";

export const GET_IMAGE_DATA = "GET_IMAGE_DATA";
export const PENDING_IMAGE_DATA = "PENDING_IMAGE_DATA";
